package bubbereatshibernate;
// Generated 03-ene-2025 8:06:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Repartidores generated by hbm2java
 */
public class Repartidores  implements java.io.Serializable {


     private Integer idRepartidor;
     private String nombreRepartidor;
     private String telefono;
     private Set pedidoses = new HashSet(0);

    public Repartidores() {
    }

	
    public Repartidores(String nombreRepartidor, String telefono) {
        this.nombreRepartidor = nombreRepartidor;
        this.telefono = telefono;
    }
    public Repartidores(String nombreRepartidor, String telefono, Set pedidoses) {
       this.nombreRepartidor = nombreRepartidor;
       this.telefono = telefono;
       this.pedidoses = pedidoses;
    }
   
    public Integer getIdRepartidor() {
        return this.idRepartidor;
    }
    
    public void setIdRepartidor(Integer idRepartidor) {
        this.idRepartidor = idRepartidor;
    }
    public String getNombreRepartidor() {
        return this.nombreRepartidor;
    }
    
    public void setNombreRepartidor(String nombreRepartidor) {
        this.nombreRepartidor = nombreRepartidor;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }




}


