package bubbereatshibernate;
// Generated 03-ene-2025 8:06:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Restaurantes generated by hbm2java
 */
public class Restaurantes  implements java.io.Serializable {


     private Integer idRestaurante;
     private String nombreRestaurante;
     private String direccion;
     private Set pedidoses = new HashSet(0);

    public Restaurantes() {
    }

	
    public Restaurantes(String nombreRestaurante, String direccion) {
        this.nombreRestaurante = nombreRestaurante;
        this.direccion = direccion;
    }
    public Restaurantes(String nombreRestaurante, String direccion, Set pedidoses) {
       this.nombreRestaurante = nombreRestaurante;
       this.direccion = direccion;
       this.pedidoses = pedidoses;
    }
   
    public Integer getIdRestaurante() {
        return this.idRestaurante;
    }
    
    public void setIdRestaurante(Integer idRestaurante) {
        this.idRestaurante = idRestaurante;
    }
    public String getNombreRestaurante() {
        return this.nombreRestaurante;
    }
    
    public void setNombreRestaurante(String nombreRestaurante) {
        this.nombreRestaurante = nombreRestaurante;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }




}


