package bubbereats;
// Generated 26-dic-2024 23:20:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer idCliente;
     private String nombreCliente;
     private String email;
     private String direccion;
     private Set pedidoses = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(String nombreCliente, String email, String direccion) {
        this.nombreCliente = nombreCliente;
        this.email = email;
        this.direccion = direccion;
    }
    public Clientes(String nombreCliente, String email, String direccion, Set pedidoses) {
       this.nombreCliente = nombreCliente;
       this.email = email;
       this.direccion = direccion;
       this.pedidoses = pedidoses;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }




}


