package bubbereats;
// Generated 26-dic-2024 23:20:35 by Hibernate Tools 4.3.1



/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer idPedido;
     private Clientes clientes;
     private Repartidores repartidores;
     private Restaurantes restaurantes;
     private String detalles;

    public Pedidos() {
    }

	
    public Pedidos(Clientes clientes, Repartidores repartidores, Restaurantes restaurantes) {
        this.clientes = clientes;
        this.repartidores = repartidores;
        this.restaurantes = restaurantes;
    }
    public Pedidos(Clientes clientes, Repartidores repartidores, Restaurantes restaurantes, String detalles) {
       this.clientes = clientes;
       this.repartidores = repartidores;
       this.restaurantes = restaurantes;
       this.detalles = detalles;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Repartidores getRepartidores() {
        return this.repartidores;
    }
    
    public void setRepartidores(Repartidores repartidores) {
        this.repartidores = repartidores;
    }
    public Restaurantes getRestaurantes() {
        return this.restaurantes;
    }
    
    public void setRestaurantes(Restaurantes restaurantes) {
        this.restaurantes = restaurantes;
    }
    public String getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(String detalles) {
        this.detalles = detalles;
    }




}


